services:
  hmpps-jobs-board-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-jobs-board-api
    ports:
      - "8080:8080"
    depends_on:
      - job-board-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,local
      - SERVER_PORT=8080
      - DATABASE_ENDPOINT=job-board-db
      - DATABASE_NAME=job-board
      - DATABASE_USERNAME=job-board
      - DATABASE_PASSWORD=job-board
      - API_BASE_URL_OAUTH=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - OS_PLACES_API_KEY=<OVERRIDE_THIS>

  job-board-db:
    image: postgres:16.2
    container_name: job-board-db
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=job-board
      - POSTGRES_USER=job-board
      - POSTGRES_DB=job-board

  localstack:
    image: localstack/localstack:4.0.3
    container_name: job-board-localstack
    ports:
      - "4566:4566"             # LocalStack Gateway
      - "4510-4559:4510-4559"   # external services port range
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  hmpps:
