version: "3"
services:
  hmpps-jobs-board-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-jobs-board-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=developer

  job-board-db:
    image: postgres
    container_name: job-board-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=job-board
      - POSTGRES_USER=job-board
      - POSTGRES_DB=job-board

  tests:
    image: cimg/postgres:15.5
    container_name: job-board-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=job-board
      - POSTGRES_USER=job-board
      - POSTGRES_DB=job-board


networks:
  hmpps:
