package uk.gov.justice.digital.hmpps.jobsboard.api.jobs.application

data class CreateJobRequest internal constructor(
  val id: String = "",
  val employerId: String,
  val title: String,
  val sector: String,
  val industrySector: String,
  val numberOfVacancies: String,
  val sourcePrimary: String,
  val sourceSecondary: String? = null,
  val charityName: String? = null,
  val postCode: String,
  val salaryFrom: String,
  val salaryTo: String? = null,
  val salaryPeriod: String,
  val additionalSalaryInformation: String? = null,
  val isPayingAtLeastNationalMinimumWage: Boolean,
  val workPattern: String,
  val hoursPerWeek: String,
  val contractType: String,
  val baseLocation: String,
  val essentialCriteria: String,
  val desirableCriteria: String? = null,
  val description: String,
  val offenceExclusions: List<String>,
  val isRollingOpportunity: Boolean,
  val closingDate: String? = null,
  val isOnlyForPrisonLeavers: Boolean,
  val startDate: String? = null,
  val howToApply: String,
  val supportingDocumentationRequired: List<String>,
  val supportingDocumentationDetails: String? = null,
) {
  companion object {
    fun from(
      id: String,
      employerId: String,
      title: String,
      sector: String,
      industrySector: String,
      numberOfVacancies: String,
      sourcePrimary: String,
      sourceSecondary: String? = null,
      charityName: String? = null,
      postCode: String,
      salaryFrom: String,
      salaryTo: String? = null,
      salaryPeriod: String,
      additionalSalaryInformation: String? = null,
      isPayingAtLeastNationalMinimumWage: Boolean,
      workPattern: String,
      hoursPerWeek: String,
      contractType: String,
      baseLocation: String,
      essentialCriteria: String,
      desirableCriteria: String? = null,
      description: String,
      offenceExclusions: List<String>,
      isRollingOpportunity: Boolean,
      closingDate: String? = null,
      isOnlyForPrisonLeavers: Boolean,
      startDate: String? = null,
      howToApply: String,
      supportingDocumentationRequired: List<String>,
      supportingDocumentationDetails: String? = null,
    ): CreateJobRequest {
      return CreateJobRequest(
        id,
        employerId,
        title,
        sector,
        industrySector,
        numberOfVacancies,
        sourcePrimary,
        sourceSecondary,
        charityName,
        postCode,
        salaryFrom,
        salaryTo,
        salaryPeriod,
        additionalSalaryInformation,
        isPayingAtLeastNationalMinimumWage,
        workPattern,
        hoursPerWeek,
        contractType,
        baseLocation,
        essentialCriteria,
        desirableCriteria,
        description,
        offenceExclusions,
        isRollingOpportunity,
        closingDate,
        isOnlyForPrisonLeavers,
        startDate,
        howToApply,
        supportingDocumentationRequired,
        supportingDocumentationDetails,
      )
    }
  }
}
