package uk.gov.justice.digital.hmpps.jobsboard.api.jobs.application

import jakarta.validation.constraints.Size

@ConsistentCopyVisibility
data class CreateJobRequest internal constructor(
  val id: String = "",
  val employerId: String,
  val jobTitle: String,
  val sector: String,
  val industrySector: String,
  val numberOfVacancies: Int,
  val sourcePrimary: String,
  val sourceSecondary: String? = null,
  val charityName: String? = null,
  val postCode: String,
  val salaryFrom: Double,
  val salaryTo: Double? = null,
  val salaryPeriod: String,
  val additionalSalaryInformation: String? = null,
  val isPayingAtLeastNationalMinimumWage: Boolean,
  val workPattern: String,
  val hoursPerWeek: String,
  val contractType: String,
  val baseLocation: String? = null,
  val essentialCriteria: String,
  val desirableCriteria: String? = null,
  val description: String,
  val offenceExclusions: List<String>,
  @field:Size(max = 500)
  val offenceExclusionsDetails: String? = null,
  val isRollingOpportunity: Boolean,
  val closingDate: String? = null,
  val isOnlyForPrisonLeavers: Boolean,
  val startDate: String? = null,
  val howToApply: String,
  val supportingDocumentationRequired: List<String>? = null,
  val supportingDocumentationDetails: String? = null,
) {
  companion object {
    fun from(
      id: String,
      employerId: String,
      jobTitle: String,
      sector: String,
      industrySector: String,
      numberOfVacancies: Int,
      sourcePrimary: String,
      sourceSecondary: String? = null,
      charityName: String? = null,
      postCode: String,
      salaryFrom: Double,
      salaryTo: Double? = null,
      salaryPeriod: String,
      additionalSalaryInformation: String? = null,
      isPayingAtLeastNationalMinimumWage: Boolean,
      workPattern: String,
      hoursPerWeek: String,
      contractType: String,
      baseLocation: String? = null,
      essentialCriteria: String,
      desirableCriteria: String? = null,
      description: String,
      offenceExclusions: List<String>,
      offenceExclusionsDetails: String? = null,
      isRollingOpportunity: Boolean,
      closingDate: String? = null,
      isOnlyForPrisonLeavers: Boolean,
      startDate: String? = null,
      howToApply: String,
      supportingDocumentationRequired: List<String>? = null,
      supportingDocumentationDetails: String? = null,
    ): CreateJobRequest = CreateJobRequest(
      id,
      employerId,
      jobTitle,
      sector,
      industrySector,
      numberOfVacancies,
      sourcePrimary,
      sourceSecondary,
      charityName,
      postCode,
      salaryFrom,
      salaryTo,
      salaryPeriod,
      additionalSalaryInformation,
      isPayingAtLeastNationalMinimumWage,
      workPattern,
      hoursPerWeek,
      contractType,
      baseLocation,
      essentialCriteria,
      desirableCriteria,
      description,
      offenceExclusions,
      offenceExclusionsDetails,
      isRollingOpportunity,
      closingDate,
      isOnlyForPrisonLeavers,
      startDate,
      howToApply,
      supportingDocumentationRequired,
      supportingDocumentationDetails,
    )
  }
}
