server:
  shutdown: immediate
  port: 8080

api:
  base.url.oauth: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
os.places.api:
  key: <OVERRIDE_THIS>

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/job-board'
    username: 'job-board'
    password: 'job-board'
  flyway:
    user: 'job-board'
    password: 'job-board'
