version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@10
parameters:
  releases-slack-channel:
    type: string
    default: education-skills-work-employment-dev
  java-version:
    type: string
    default: "21.0"
  postgres-version:
    type: string
    default: "16.2"
  localstack-version:
    type: string
    default: "4"
jobs:
  validate:
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: << pipeline.parameters.java-version >>
      postgres_tag: << pipeline.parameters.postgres-version >>
      postgres_db: "job-board"
      postgres_username: "job-board"
      postgres_password: "job-board"
      localstack_tag: << pipeline.parameters.localstack-version >>
      services: "sqs"
    environment:
      DATABASE_ENDPOINT: localhost
      DATABASE_NAME: job-board
      DATABASE_USERNAME: job-board
      DATABASE_PASSWORD: job-board
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - hmpps/wait_till_ready_postgres
      - run:
          command: ./gradlew --daemon check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  test-only:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
