package uk.gov.justice.digital.hmpps.jobsboard.api.enums

enum class TypeOfWork {
  OUTDOOR,
  CONSTRUCTION,
  DRIVING,
  BEAUTY,
  HOSPITALITY,
  TECHNICAL,
  MANUFACTURING,
  OFFICE,
  RETAIL,
  SPORTS,
  WAREHOUSING,
  EDUCATION_TRAINING,
  WASTE_MANAGEMENT,
  CLEANING_AND_MAINTENANCE,
}
