server:
  shutdown: immediate

api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  integration:
    enabled: true

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  jpa:
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:job-board}?sslmode=disable&autosave=conservative'
    user: '${DATABASE_USERNAME:job-board}'
    password: '${DATABASE_PASSWORD:job-board}'
  flyway:
    baseline-on-migrate: true
    clean-disabled: false
os:
  places:
    api:
      url: http://localhost:8093
      key: "os-places-api-key"

hmpps.sqs:
  provider: localstack
  queues:
    outboundintegrationqueue:
      queueName: ${random.uuid}
