server:
  shutdown: immediate

api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:job-board}?sslmode=disable&autosave=conservative'
    username: '${DATABASE_USERNAME:job-board}'
    password: '${DATABASE_PASSWORD:job-board}'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

os:
  places:
    api:
      url: http://localhost:8093
      key: "os-places-api-key"

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
