---
# Per environment values which override defaults in hmpps-jobs-board-api/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: jobs-board-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_BASE_URL_OAUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    OS_PLACES_API_URL: "https://api.os.uk/search/places/v1"
    API_INTEGRATION_ENABLED: true
    HMPPS_SAR_ADDITIONALACCESSROLE: "ROLE_EDUCATION_WORK_PLAN_VIEW"

  serviceAccountName: education-skills-and-work-devs-development

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: education-alerts-non-prod
  businessHoursOnly: true
