---
# Per environment values which override defaults in hmpps-jobs-board-api/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: jobs-board-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_BASE_URL_OAUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    OS_PLACES_API_URL: "https://api.os.uk/search/places/v1"
    API_INTEGRATION_ENABLED: true

  serviceAccountName: education-skills-work-employment-development

  namespace_secrets:
    sqs-integration:
      HMPPS_SQS_QUEUES_OUTBOUNDINTEGRATIONQUEUE_QUEUE_NAME: "outboundintegrationqueue"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
