ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS is_national BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE jobs ALTER COLUMN postcode DROP NOT NULL;

ALTER TABLE jobs ADD CHECK (is_national = TRUE OR postcode IS NOT NULL);
